version: "3"


vars:
  target: kobra
  src: doomgeneric
  binary: kobradoom


tasks:
  .make:*:
    internal: true
    dir: "{{ .src }}"
    cmds:
      - make -f Makefile.{{ .target }} -j{{ numCPU }} {{ index .MATCH 0 }}

  submodule:
    desc: Initialize submodules.
    status:
      - test -d rv1106-cross-compilation-toolchain
    cmds:
      - git submodule update --init

  clean:
    desc: Clean current build artifacts.
    cmds:
      - task: .make:clean

  default:
    desc: Build for Kobra.
    run: once
    deps:
      - submodule
    sources:
      - doomgeneric_kobra.c
      - Makefile.kobra
      - '*.c'
      - '*.h'
    generates:
      - '{{ .binary }}'
    cmds:
      - task: '.make:'

  deploy:
    desc: Deploy to target Kobra.
    deps:
      - default
    preconditions:
      - test -f {{ .src }}/{{ .binary }}
    cmds:
      - scp {{ .src }}/{{ .binary }} {{ .target }}:/tmp/
