version: "3"

vars:
  target: kobra
  src: doomgeneric/
  binary: kobradoom

tasks:
  submodule:
    desc: Initialize submodules
    status:
      - test -d rv1106-cross-compilation-toolchain
    cmds:
      - git submodule update --init

  default:
    desc: Clean and build for Kobra (force a rebuild with --force)
    dir: "{{ .src }}"
    status:
      - test -f {{ .binary }}
      - '[[ "{{ .CLI_FORCE }}" == "false" ]]'
    cmds:
      - task: submodule
      - make -f Makefile.{{ .target }} -j{{ numCPU }} clean
      - make -f Makefile.{{ .target }} -j{{ numCPU }}

  deploy:
    desc: Deploy to target Kobra
    dir: "{{ .src }}"
    cmds:
      - task: default
      - scp {{ .binary }} {{ .target }}:/tmp/
